behaviors: 
  My Behavior: 
    trainer_type: ppo
    summary_freq: 500
    time_horizon: 1
    max_steps: 500000
    keep_checkpoints: 5
    even_checkpoints: true
    checkpoint_interval: 1000

    hyperparameters:
      learning_rate: 5.0e-4
      batch_size: 512
      buffer_size: 10240
      learning_rate_schedule: linear

      beta: 5.0e-3
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 10
      
    network_settings:
      hidden_units: 256
      num_layers: 2
      normalize: true
      torch_device: cuda

    reward_signals:
      extrinsic:
        gamma: 0.0
        strength: 1.0